security:
  encoders:
    App\Entity\User:
      algorithm: argon2i

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # see: https://symfony.com/doc/current/security/form_login_setup.html
    main:
      anonymous: true
      form_login:
        check_path: app_security_login
        login_path: app_security_login
        csrf_token_generator: security.csrf.token_manager
        default_target_path: app_security_login_redirect
        provider: app_user_provider

      guard:
        authenticators:
        - App\Security\LoginFormAuthenticator

      logout: {path: /logout, target: /login}

  # Roles
  role_hierarchy:
    ROLE_MANAGER:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_MANAGER]

  # Easy way to control access for large sections of your site
  access_control:
  - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/user, roles: ROLE_SUPER_ADMIN }
  - { path: ^/, roles: ROLE_USER }

