version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=bdd_ebitda_calendar
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=nimda1234
    ports:
    - "5432:5432"

volumes:
  db-data: {}